export interface SymbolItem {
    name: string;
    latex: string;
}

export const mathSymbols: SymbolItem[] = [
    { name: "Addition", latex: "+" },
    { name: "Subtraction", latex: "-" },
    { name: "Multiplication", latex: "\\times" },
    { name: "Division", latex: "\\div" },
    { name: "Fraction", latex: "\\frac{a}{b}" },
    { name: "Square Root", latex: "\\sqrt{x}" },
    { name: "N-th Root", latex: "\\sqrt[n]{x}" },
    { name: "Summation", latex: "\\sum_{i=1}^{n}" },
    { name: "Product", latex: "\\prod_{i=1}^{n}" },
    { name: "Integral", latex: "\\int_{a}^{b}" },
    { name: "Limit", latex: "\\lim_{x \\to \\infty}" },
    { name: "Infinity", latex: "\\infty" },
    { name: "Approximately Equal", latex: "\\approx" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "Less Than or Equal", latex: "\\leq" },
    { name: "Greater Than or Equal", latex: "\\geq" },
    { name: "Implies", latex: "\\implies" },
    { name: "Equivalent", latex: "\\iff" },
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Subset", latex: "\\subset" },
    { name: "Union", latex: "\\cup" },
    { name: "Intersection", latex: "\\cap" },
    { name: "Empty Set", latex: "\\emptyset" },
    { name: "Partial Derivative", latex: "\\partial" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Plus Minus", latex: "\\pm" },
    { name: "Dot Product", latex: "\\cdot" },
];

export const greekSymbols: SymbolItem[] = [
    { name: "Alpha", latex: "\\alpha" },
    { name: "Beta", latex: "\\beta" },
    { name: "Gamma", latex: "\\gamma" },
    { name: "Gamma (Upper)", latex: "\\Gamma" },
    { name: "Delta", latex: "\\delta" },
    { name: "Delta (Upper)", latex: "\\Delta" },
    { name: "Epsilon", latex: "\\epsilon" },
    { name: "Epsilon (Variant)", latex: "\\varepsilon" },
    { name: "Zeta", latex: "\\zeta" },
    { name: "Eta", latex: "\\eta" },
    { name: "Theta", latex: "\\theta" },
    { name: "Theta (Upper)", latex: "\\Theta" },
    { name: "Iota", latex: "\\iota" },
    { name: "Kappa", latex: "\\kappa" },
    { name: "Lambda", latex: "\\lambda" },
    { name: "Lambda (Upper)", latex: "\\Lambda" },
    { name: "Mu", latex: "\\mu" },
    { name: "Nu", latex: "\\nu" },
    { name: "Xi", latex: "\\xi" },
    { name: "Xi (Upper)", latex: "\\Xi" },
    { name: "Pi", latex: "\\pi" },
    { name: "Pi (Upper)", latex: "\\Pi" },
    { name: "Rho", latex: "\\rho" },
    { name: "Sigma", latex: "\\sigma" },
    { name: "Sigma (Upper)", latex: "\\Sigma" },
    { name: "Tau", latex: "\\tau" },
    { name: "Upsilon", latex: "\\upsilon" },
    { name: "Upsilon (Upper)", latex: "\\Upsilon" },
    { name: "Phi", latex: "\\phi" },
    { name: "Phi (Upper)", latex: "\\Phi" },
    { name: "Chi", latex: "\\chi" },
    { name: "Psi", latex: "\\psi" },
    { name: "Psi (Upper)", latex: "\\Psi" },
    { name: "Omega", latex: "\\omega" },
    { name: "Omega (Upper)", latex: "\\Omega" },
];

export const arrowSymbols: SymbolItem[] = [
    { name: "Left Arrow", latex: "\\leftarrow" },
    { name: "Right Arrow", latex: "\\rightarrow" },
    { name: "Up Arrow", latex: "\\uparrow" },
    { name: "Long Left Arrow", latex: "\\longleftarrow" },
    { name: "Long Right Arrow", latex: "\\longrightarrow" },
    { name: "Down Arrow", latex: "\\downarrow" },
    { name: "Left Arrow (Double)", latex: "\\Leftarrow" },
    { name: "Right Arrow (Double)", latex: "\\Rightarrow" },
    { name: "Up Arrow (Double)", latex: "\\Uparrow" },
    { name: "Long Left Arrow (Double)", latex: "\\Longleftarrow" },
    { name: "Long Right Arrow (Double)", latex: "\\Longrightarrow" },
    { name: "Down Arrow (Double)", latex: "\\Downarrow" },
    { name: "Left Right Arrow", latex: "\\leftrightarrow" },
    { name: "Long Left Right Arrow", latex: "\\longleftrightarrow" },
    { name: "Up Down Arrow", latex: "\\updownarrow" },
    { name: "Left Right Arrow (Double)", latex: "\\Leftrightarrow" },
    { name: "Long Left Right Arrow (Double)", latex: "\\Longleftrightarrow" },
    { name: "Up Down Arrow (Double)", latex: "\\Updownarrow" },
    { name: "Maps To", latex: "\\mapsto" },
    { name: "Long Maps To", latex: "\\longmapsto" },
    { name: "Near Arrow", latex: "\\nearrow" },
    { name: "Hook Left Arrow", latex: "\\hookleftarrow" },
    { name: "Hook Right Arrow", latex: "\\hookrightarrow" },
    { name: "Search Arrow", latex: "\\searrow" },
    { name: "Left Harpoon Up", latex: "\\leftharpoonup" },
    { name: "Right Harpoon Up", latex: "\\rightharpoonup" },
    { name: "Southwest Arrow", latex: "\\swarrow" },
    { name: "Left Harpoon Down", latex: "\\leftharpoondown" },
    { name: "Right Harpoon Down", latex: "\\rightharpoondown" },
    { name: "Northwest Arrow", latex: "\\nwarrow" },
];

export const latinSymbols: SymbolItem[] = [
    { name: "ö", latex: "\\ddot{o}" },
    { name: "ò", latex: "\\grave{o}" },
    { name: "ó", latex: "\\acute{o}" },
    { name: "ô", latex: "\\hat{o}" },
    { name: "õ", latex: "\\tilde{o}" },
    { name: "ō", latex: "\\bar{o}" },
    { name: "ȯ", latex: "\\dot{o}" },
    { name: "ŏ", latex: "\\breve{o}" },
    { name: "ǒ", latex: "\\check{o}" },
    { name: "ő", latex: "\\H{o}" },
    { name: "o̧", latex: "\\text{o̧}" },
    { name: "ọ", latex: "\\text{ọ}" },
    { name: "o̲", latex: "\\underline{o}" },
    { name: "oo", latex: "o\\!\\!-\\!\\!o" },
    { name: "œ", latex: "\\text{œ}" },
    { name: "Œ", latex: "\\text{Œ}" },
    { name: "æ", latex: "\\text{æ}" },
    { name: "Æ", latex: "\\text{Æ}" },
    { name: "å", latex: "\\text{å}" },
    { name: "Å", latex: "\\text{Å}" },
    { name: "ø", latex: "\\text{ø}" },
    { name: "Ø", latex: "\\text{Ø}" },
    { name: "ł", latex: "\\text{ł}" },
    { name: "Ł", latex: "\\text{Ł}" },
    { name: "ı", latex: "\\imath" },
    { name: "ȷ", latex: "\\jmath" },
    { name: "¿", latex: "\\text{¿}" },
    { name: "¡", latex: "\\text{¡}" },
];

// Set Theory Symbols
export const setTheorySymbols: SymbolItem[] = [
    { name: "Empty Set", latex: "\\emptyset" },
    { name: "Empty Set (Variant)", latex: "\\varnothing" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Contains", latex: "\\ni" },
    { name: "Subset", latex: "\\subset" },
    { name: "Subset or Equal", latex: "\\subseteq" },
    { name: "Not Subset", latex: "\\not\\subset" },
    { name: "Proper Subset", latex: "\\subsetneq" },
    { name: "Superset", latex: "\\supset" },
    { name: "Superset or Equal", latex: "\\supseteq" },
    { name: "Union", latex: "\\cup" },
    { name: "Intersection", latex: "\\cap" },
    { name: "Big Union", latex: "\\bigcup" },
    { name: "Big Intersection", latex: "\\bigcap" },
    { name: "Set Difference", latex: "\\setminus" },
    { name: "Complement", latex: "\\complement" },
    { name: "Natural Numbers", latex: "\\mathbb{N}" },
    { name: "Integers", latex: "\\mathbb{Z}" },
    { name: "Rational Numbers", latex: "\\mathbb{Q}" },
    { name: "Real Numbers", latex: "\\mathbb{R}" },
    { name: "Complex Numbers", latex: "\\mathbb{C}" },
    { name: "Power Set", latex: "\\mathcal{P}" },
    { name: "Cardinality", latex: "|A|" },
    { name: "Aleph", latex: "\\aleph" },
];

// Logic & Proof Symbols
export const logicSymbols: SymbolItem[] = [
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Not Exists", latex: "\\nexists" },
    { name: "Negation", latex: "\\neg" },
    { name: "Logical And", latex: "\\land" },
    { name: "Logical Or", latex: "\\lor" },
    { name: "Implies", latex: "\\Rightarrow" },
    { name: "Implied By", latex: "\\Leftarrow" },
    { name: "If and Only If", latex: "\\Leftrightarrow" },
    { name: "Long Implies", latex: "\\implies" },
    { name: "Long Iff", latex: "\\iff" },
    { name: "Proves", latex: "\\vdash" },
    { name: "Models", latex: "\\models" },
    { name: "Therefore", latex: "\\therefore" },
    { name: "Because", latex: "\\because" },
    { name: "Contradiction", latex: "\\bot" },
    { name: "Tautology", latex: "\\top" },
    { name: "QED", latex: "\\square" },
    { name: "Equivalent", latex: "\\equiv" },
    { name: "Not Equivalent", latex: "\\not\\equiv" },
];

// Linear Algebra Symbols
export const linearAlgebraSymbols: SymbolItem[] = [
    { name: "Vector", latex: "\\vec{x}" },
    { name: "Bold Vector", latex: "\\mathbf{x}" },
    { name: "Hat Vector", latex: "\\hat{x}" },
    { name: "Transpose", latex: "A^{\\top}" },
    { name: "Transpose (T)", latex: "A^T" },
    { name: "Inverse", latex: "A^{-1}" },
    { name: "Determinant", latex: "\\det(A)" },
    { name: "Determinant Bars", latex: "|A|" },
    { name: "Trace", latex: "\\text{tr}(A)" },
    { name: "Rank", latex: "\\text{rank}(A)" },
    { name: "Norm", latex: "\\lVert x \\rVert" },
    { name: "Norm (Double)", latex: "\\| x \\|" },
    { name: "Inner Product", latex: "\\langle x, y \\rangle" },
    { name: "Tensor Product", latex: "\\otimes" },
    { name: "Direct Sum", latex: "\\oplus" },
    { name: "Dot Product", latex: "\\cdot" },
    { name: "Cross Product", latex: "\\times" },
    { name: "Kronecker Delta", latex: "\\delta_{ij}" },
    { name: "Identity Matrix", latex: "I_n" },
    { name: "Zero Matrix", latex: "\\mathbf{0}" },
    { name: "Eigenvalue", latex: "\\lambda" },
    { name: "Matrix", latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}" },
    { name: "Column Vector", latex: "\\begin{pmatrix} x \\\\ y \\end{pmatrix}" },
];

// Calculus & Analysis Symbols
export const calculusSymbols: SymbolItem[] = [
    { name: "Partial Derivative", latex: "\\partial" },
    { name: "Nabla/Gradient", latex: "\\nabla" },
    { name: "Integral", latex: "\\int" },
    { name: "Definite Integral", latex: "\\int_{a}^{b}" },
    { name: "Double Integral", latex: "\\iint" },
    { name: "Triple Integral", latex: "\\iiint" },
    { name: "Contour Integral", latex: "\\oint" },
    { name: "Derivative", latex: "\\frac{d}{dx}" },
    { name: "Partial Derivative Frac", latex: "\\frac{\\partial}{\\partial x}" },
    { name: "Limit", latex: "\\lim_{x \\to a}" },
    { name: "Limit to Infinity", latex: "\\lim_{x \\to \\infty}" },
    { name: "Infinity", latex: "\\infty" },
    { name: "Summation", latex: "\\sum_{n=1}^{\\infty}" },
    { name: "Product", latex: "\\prod_{n=1}^{\\infty}" },
    { name: "Differential", latex: "dx" },
    { name: "Prime Derivative", latex: "f'(x)" },
    { name: "Double Prime", latex: "f''(x)" },
    { name: "Dot Derivative", latex: "\\dot{x}" },
    { name: "Double Dot", latex: "\\ddot{x}" },
    { name: "Approaches", latex: "\\to" },
    { name: "Evaluated At", latex: "\\Big|_{a}^{b}" },
];

// Probability & Statistics Symbols
export const probabilitySymbols: SymbolItem[] = [
    { name: "Probability", latex: "\\mathbb{P}" },
    { name: "Probability of A", latex: "P(A)" },
    { name: "Expectation", latex: "\\mathbb{E}[X]" },
    { name: "Expectation (E)", latex: "E[X]" },
    { name: "Variance", latex: "\\text{Var}(X)" },
    { name: "Covariance", latex: "\\text{Cov}(X,Y)" },
    { name: "Standard Deviation", latex: "\\sigma" },
    { name: "Mean", latex: "\\mu" },
    { name: "Sample Mean", latex: "\\bar{x}" },
    { name: "Distributed As", latex: "\\sim" },
    { name: "Normal Distribution", latex: "\\mathcal{N}(\\mu, \\sigma^2)" },
    { name: "Independent", latex: "\\perp" },
    { name: "Independent (Double)", latex: "\\perp\\!\\!\\!\\perp" },
    { name: "Conditional", latex: "\\mid" },
    { name: "Given", latex: "P(A \\mid B)" },
    { name: "Correlation", latex: "\\rho" },
    { name: "Chi-Squared", latex: "\\chi^2" },
    { name: "Binomial Coefficient", latex: "\\binom{n}{k}" },
    { name: "Factorial", latex: "n!" },
    { name: "Proportional To", latex: "\\propto" },
];

// Computer Science / Algorithms Symbols
export const csSymbols: SymbolItem[] = [
    { name: "Big O", latex: "O(n)" },
    { name: "Big Omega", latex: "\\Omega(n)" },
    { name: "Big Theta", latex: "\\Theta(n)" },
    { name: "Little o", latex: "o(n)" },
    { name: "Little omega", latex: "\\omega(n)" },
    { name: "Maps To", latex: "\\mapsto" },
    { name: "Assignment", latex: ":=" },
    { name: "Definition", latex: "\\triangleq" },
    { name: "Equivalent", latex: "\\equiv" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "XOR", latex: "\\oplus" },
    { name: "Logical And", latex: "\\land" },
    { name: "Logical Or", latex: "\\lor" },
    { name: "Negation", latex: "\\neg" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Modulo", latex: "\\bmod" },
    { name: "Divides", latex: "\\mid" },
    { name: "Does Not Divide", latex: "\\nmid" },
    { name: "Asterisk", latex: "\\ast" },
    { name: "Star", latex: "\\star" },
    { name: "Logarithm", latex: "\\log" },
    { name: "Natural Log", latex: "\\ln" },
];

// Number Theory Symbols
export const numberTheorySymbols: SymbolItem[] = [
    { name: "Divides", latex: "\\mid" },
    { name: "Does Not Divide", latex: "\\nmid" },
    { name: "GCD", latex: "\\gcd(a, b)" },
    { name: "LCM", latex: "\\text{lcm}(a, b)" },
    { name: "Congruent", latex: "\\equiv" },
    { name: "Modulo", latex: "\\pmod{n}" },
    { name: "Euler Phi", latex: "\\varphi(n)" },
    { name: "Phi Function", latex: "\\phi(n)" },
    { name: "Prime", latex: "p" },
    { name: "Prime Notation", latex: "p_n" },
    { name: "Coprime", latex: "\\perp" },
    { name: "Legendre Symbol", latex: "\\left(\\frac{a}{p}\\right)" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Integer Part", latex: "[x]" },
    { name: "Fractional Part", latex: "\\{x\\}" },
    { name: "Sum of Divisors", latex: "\\sigma(n)" },
    { name: "Mobius Function", latex: "\\mu(n)" },
    { name: "Number of Divisors", latex: "d(n)" },
];

// Physics Symbols
export const physicsSymbols: SymbolItem[] = [
    { name: "Planck Constant", latex: "\\hbar" },
    { name: "Bra", latex: "\\langle \\psi |" },
    { name: "Ket", latex: "| \\psi \\rangle" },
    { name: "Braket", latex: "\\langle \\phi | \\psi \\rangle" },
    { name: "Delta", latex: "\\Delta" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Laplacian", latex: "\\nabla^2" },
    { name: "D'Alembertian", latex: "\\Box" },
    { name: "Lagrangian", latex: "\\mathcal{L}" },
    { name: "Hamiltonian", latex: "\\mathcal{H}" },
    { name: "Wave Function", latex: "\\Psi" },
    { name: "Angular Frequency", latex: "\\omega" },
    { name: "Wavelength", latex: "\\lambda" },
    { name: "Tensor", latex: "T^{\\mu\\nu}" },
    { name: "Christoffel Symbol", latex: "\\Gamma^{\\lambda}_{\\mu\\nu}" },
    { name: "Partial Time", latex: "\\frac{\\partial}{\\partial t}" },
    { name: "Vector Field", latex: "\\vec{E}" },
    { name: "Cross Product", latex: "\\times" },
    { name: "Divergence", latex: "\\nabla \\cdot" },
    { name: "Curl", latex: "\\nabla \\times" },
];

// Chemistry Symbols
export const chemistrySymbols: SymbolItem[] = [
    { name: "Equilibrium Arrow", latex: "\\rightleftharpoons" },
    { name: "Reversible Reaction", latex: "\\leftrightarrows" },
    { name: "Right Arrow", latex: "\\rightarrow" },
    { name: "Yields", latex: "\\longrightarrow" },
    { name: "Up Arrow (Gas)", latex: "\\uparrow" },
    { name: "Down Arrow (Precipitate)", latex: "\\downarrow" },
    { name: "Isotope", latex: "{}^{14}_{6}\\text{C}" },
    { name: "Superscript Charge", latex: "\\text{Na}^{+}" },
    { name: "Subscript Count", latex: "\\text{H}_2\\text{O}" },
    { name: "Delta (Heat)", latex: "\\Delta" },
    { name: "Degree", latex: "^{\\circ}" },
    { name: "Celsius", latex: "^{\\circ}\\text{C}" },
    { name: "Bond", latex: "\\text{C}-\\text{C}" },
    { name: "Double Bond", latex: "\\text{C}=\\text{C}" },
    { name: "Triple Bond", latex: "\\text{C}\\equiv\\text{C}" },
    { name: "Partial Charge", latex: "\\delta^{+}" },
    { name: "Electron", latex: "e^{-}" },
    { name: "Aqueous", latex: "\\text{(aq)}" },
    { name: "Solid", latex: "\\text{(s)}" },
    { name: "Liquid", latex: "\\text{(l)}" },
    { name: "Gas", latex: "\\text{(g)}" },
];

// Brackets & Delimiters
export const bracketSymbols: SymbolItem[] = [
    { name: "Angle Bracket Left", latex: "\\langle" },
    { name: "Angle Bracket Right", latex: "\\rangle" },
    { name: "Angle Brackets", latex: "\\langle x \\rangle" },
    { name: "Ceiling Left", latex: "\\lceil" },
    { name: "Ceiling Right", latex: "\\rceil" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Floor Left", latex: "\\lfloor" },
    { name: "Floor Right", latex: "\\rfloor" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Double Vertical Bar", latex: "\\|" },
    { name: "Norm", latex: "\\| x \\|" },
    { name: "Double Bracket Left", latex: "\\llbracket" },
    { name: "Double Bracket Right", latex: "\\rrbracket" },
    { name: "Double Brackets", latex: "\\llbracket x \\rrbracket" },
    { name: "Parentheses", latex: "\\left( x \\right)" },
    { name: "Square Brackets", latex: "\\left[ x \\right]" },
    { name: "Curly Braces", latex: "\\left\\{ x \\right\\}" },
    { name: "Vertical Bar", latex: "\\left| x \\right|" },
    { name: "Big Parentheses", latex: "\\Big( x \\Big)" },
    { name: "Bigg Parentheses", latex: "\\Bigg( x \\Bigg)" },
    { name: "Left Only", latex: "\\left( x \\right." },
    { name: "Right Only", latex: "\\left. x \\right)" },
    { name: "Mixed Brackets", latex: "\\left[ x \\right)" },
];

// Accents & Modifiers
export const accentSymbols: SymbolItem[] = [
    { name: "Hat", latex: "\\hat{x}" },
    { name: "Wide Hat", latex: "\\widehat{xyz}" },
    { name: "Tilde", latex: "\\tilde{x}" },
    { name: "Wide Tilde", latex: "\\widetilde{xyz}" },
    { name: "Dot", latex: "\\dot{x}" },
    { name: "Double Dot", latex: "\\ddot{x}" },
    { name: "Triple Dot", latex: "\\dddot{x}" },
    { name: "Bar", latex: "\\bar{x}" },
    { name: "Overline", latex: "\\overline{xyz}" },
    { name: "Underline", latex: "\\underline{xyz}" },
    { name: "Vector Arrow", latex: "\\vec{x}" },
    { name: "Wide Vector", latex: "\\overrightarrow{AB}" },
    { name: "Left Vector", latex: "\\overleftarrow{AB}" },
    { name: "Double Arrow", latex: "\\overleftrightarrow{AB}" },
    { name: "Acute", latex: "\\acute{x}" },
    { name: "Grave", latex: "\\grave{x}" },
    { name: "Breve", latex: "\\breve{x}" },
    { name: "Check", latex: "\\check{x}" },
    { name: "Ring", latex: "\\mathring{x}" },
    { name: "Overbrace", latex: "\\overbrace{x+y}^{\\text{sum}}" },
    { name: "Underbrace", latex: "\\underbrace{x+y}_{\\text{sum}}" },
    { name: "Cancel", latex: "\\cancel{x}" },
    { name: "Box", latex: "\\boxed{x}" },
];

// Currency & Finance Symbols
export const financeSymbols: SymbolItem[] = [
    { name: "Dollar", latex: "\\$" },
    { name: "Euro", latex: "\\text{€}" },
    { name: "Pound", latex: "\\text{£}" },
    { name: "Yen", latex: "\\text{¥}" },
    { name: "Rupee", latex: "\\text{₹}" },
    { name: "Bitcoin", latex: "\\text{₿}" },
    { name: "Percent", latex: "\\%" },
    { name: "Per Mille", latex: "\\text{‰}" },
    { name: "Basis Point", latex: "\\text{bp}" },
    { name: "NPV", latex: "\\text{NPV}" },
    { name: "IRR", latex: "\\text{IRR}" },
    { name: "ROI", latex: "\\text{ROI}" },
    { name: "Summation", latex: "\\sum_{t=1}^{n}" },
    { name: "Present Value", latex: "\\frac{C}{(1+r)^t}" },
    { name: "Compound Interest", latex: "A = P(1 + r/n)^{nt}" },
    { name: "Continuous Compounding", latex: "A = Pe^{rt}" },
    { name: "Greater Than", latex: ">" },
    { name: "Less Than", latex: "<" },
    { name: "Approximately", latex: "\\approx" },
    { name: "Plus Minus", latex: "\\pm" },
];