export interface SymbolItem {
    name: string;
    latex: string;
}

export const mathSymbols: SymbolItem[] = [
    { name: "Addition", latex: "+" },
    { name: "Subtraction", latex: "-" },
    { name: "Multiplication", latex: "\\times" },
    { name: "Division", latex: "\\div" },
    { name: "Fraction", latex: "\\frac{a}{b}" },
    { name: "Square Root", latex: "\\sqrt{x}" },
    { name: "N-th Root", latex: "\\sqrt[n]{x}" },
    { name: "Summation", latex: "\\sum_{i=1}^{n}" },
    { name: "Product", latex: "\\prod_{i=1}^{n}" },
    { name: "Integral", latex: "\\int_{a}^{b}" },
    { name: "Limit", latex: "\\lim_{x \\to \\infty}" },
    { name: "Infinity", latex: "\\infty" },
    { name: "Approximately Equal", latex: "\\approx" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "Less Than or Equal", latex: "\\leq" },
    { name: "Greater Than or Equal", latex: "\\geq" },
    { name: "Implies", latex: "\\implies" },
    { name: "Equivalent", latex: "\\iff" },
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Subset", latex: "\\subset" },
    { name: "Union", latex: "\\cup" },
    { name: "Intersection", latex: "\\cap" },
    { name: "Empty Set", latex: "\\emptyset" },
    { name: "Partial Derivative", latex: "\\partial" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Plus Minus", latex: "\\pm" },
    { name: "Dot Product", latex: "\\cdot" },
];

export const greekSymbols: SymbolItem[] = [
    { name: "Alpha", latex: "\\alpha" },
    { name: "Beta", latex: "\\beta" },
    { name: "Gamma", latex: "\\gamma" },
    { name: "Gamma (Upper)", latex: "\\Gamma" },
    { name: "Delta", latex: "\\delta" },
    { name: "Delta (Upper)", latex: "\\Delta" },
    { name: "Epsilon", latex: "\\epsilon" },
    { name: "Epsilon (Variant)", latex: "\\varepsilon" },
    { name: "Zeta", latex: "\\zeta" },
    { name: "Eta", latex: "\\eta" },
    { name: "Theta", latex: "\\theta" },
    { name: "Theta (Upper)", latex: "\\Theta" },
    { name: "Iota", latex: "\\iota" },
    { name: "Kappa", latex: "\\kappa" },
    { name: "Lambda", latex: "\\lambda" },
    { name: "Lambda (Upper)", latex: "\\Lambda" },
    { name: "Mu", latex: "\\mu" },
    { name: "Nu", latex: "\\nu" },
    { name: "Xi", latex: "\\xi" },
    { name: "Xi (Upper)", latex: "\\Xi" },
    { name: "Pi", latex: "\\pi" },
    { name: "Pi (Upper)", latex: "\\Pi" },
    { name: "Rho", latex: "\\rho" },
    { name: "Sigma", latex: "\\sigma" },
    { name: "Sigma (Upper)", latex: "\\Sigma" },
    { name: "Tau", latex: "\\tau" },
    { name: "Upsilon", latex: "\\upsilon" },
    { name: "Upsilon (Upper)", latex: "\\Upsilon" },
    { name: "Phi", latex: "\\phi" },
    { name: "Phi (Upper)", latex: "\\Phi" },
    { name: "Chi", latex: "\\chi" },
    { name: "Psi", latex: "\\psi" },
    { name: "Psi (Upper)", latex: "\\Psi" },
    { name: "Omega", latex: "\\omega" },
    { name: "Omega (Upper)", latex: "\\Omega" },
];
