export interface SymbolItem {
    name: string;
    latex: string;
}

export const mathSymbols: SymbolItem[] = [
    { name: "Addition", latex: "+" },
    { name: "Subtraction", latex: "-" },
    { name: "Multiplication", latex: "\\times" },
    { name: "Division", latex: "\\div" },
    { name: "Fraction", latex: "\\frac{a}{b}" },
    { name: "Square Root", latex: "\\sqrt{x}" },
    { name: "N-th Root", latex: "\\sqrt[n]{x}" },
    { name: "Summation", latex: "\\sum_{i=1}^{n}" },
    { name: "Product", latex: "\\prod_{i=1}^{n}" },
    { name: "Integral", latex: "\\int_{a}^{b}" },
    { name: "Limit", latex: "\\lim_{x \\to \\infty}" },
    { name: "Infinity", latex: "\\infty" },
    { name: "Approximately Equal", latex: "\\approx" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "Less Than or Equal", latex: "\\leq" },
    { name: "Greater Than or Equal", latex: "\\geq" },
    { name: "Implies", latex: "\\implies" },
    { name: "Equivalent", latex: "\\iff" },
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Subset", latex: "\\subset" },
    { name: "Union", latex: "\\cup" },
    { name: "Intersection", latex: "\\cap" },
    { name: "Empty Set", latex: "\\emptyset" },
    { name: "Partial Derivative", latex: "\\partial" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Plus Minus", latex: "\\pm" },
    { name: "Dot Product", latex: "\\cdot" },
];

export const greekSymbols: SymbolItem[] = [
    { name: "Alpha", latex: "\\alpha" },
    { name: "Beta", latex: "\\beta" },
    { name: "Gamma", latex: "\\gamma" },
    { name: "Gamma (Upper)", latex: "\\Gamma" },
    { name: "Delta", latex: "\\delta" },
    { name: "Delta (Upper)", latex: "\\Delta" },
    { name: "Epsilon", latex: "\\epsilon" },
    { name: "Epsilon (Variant)", latex: "\\varepsilon" },
    { name: "Zeta", latex: "\\zeta" },
    { name: "Eta", latex: "\\eta" },
    { name: "Theta", latex: "\\theta" },
    { name: "Theta (Upper)", latex: "\\Theta" },
    { name: "Iota", latex: "\\iota" },
    { name: "Kappa", latex: "\\kappa" },
    { name: "Lambda", latex: "\\lambda" },
    { name: "Lambda (Upper)", latex: "\\Lambda" },
    { name: "Mu", latex: "\\mu" },
    { name: "Nu", latex: "\\nu" },
    { name: "Xi", latex: "\\xi" },
    { name: "Xi (Upper)", latex: "\\Xi" },
    { name: "Pi", latex: "\\pi" },
    { name: "Pi (Upper)", latex: "\\Pi" },
    { name: "Rho", latex: "\\rho" },
    { name: "Sigma", latex: "\\sigma" },
    { name: "Sigma (Upper)", latex: "\\Sigma" },
    { name: "Tau", latex: "\\tau" },
    { name: "Upsilon", latex: "\\upsilon" },
    { name: "Upsilon (Upper)", latex: "\\Upsilon" },
    { name: "Phi", latex: "\\phi" },
    { name: "Phi (Upper)", latex: "\\Phi" },
    { name: "Chi", latex: "\\chi" },
    { name: "Psi", latex: "\\psi" },
    { name: "Psi (Upper)", latex: "\\Psi" },
    { name: "Omega", latex: "\\omega" },
    { name: "Omega (Upper)", latex: "\\Omega" },
];

export const arrowSymbols: SymbolItem[] = [
    { name: "Left Arrow", latex: "\\leftarrow" },
    { name: "Right Arrow", latex: "\\rightarrow" },
    { name: "Up Arrow", latex: "\\uparrow" },
    { name: "Long Left Arrow", latex: "\\longleftarrow" },
    { name: "Long Right Arrow", latex: "\\longrightarrow" },
    { name: "Down Arrow", latex: "\\downarrow" },
    { name: "Left Arrow (Double)", latex: "\\Leftarrow" },
    { name: "Right Arrow (Double)", latex: "\\Rightarrow" },
    { name: "Up Arrow (Double)", latex: "\\Uparrow" },
    { name: "Long Left Arrow (Double)", latex: "\\Longleftarrow" },
    { name: "Long Right Arrow (Double)", latex: "\\Longrightarrow" },
    { name: "Down Arrow (Double)", latex: "\\Downarrow" },
    { name: "Left Right Arrow", latex: "\\leftrightarrow" },
    { name: "Long Left Right Arrow", latex: "\\longleftrightarrow" },
    { name: "Up Down Arrow", latex: "\\updownarrow" },
    { name: "Left Right Arrow (Double)", latex: "\\Leftrightarrow" },
    { name: "Long Left Right Arrow (Double)", latex: "\\Longleftrightarrow" },
    { name: "Up Down Arrow (Double)", latex: "\\Updownarrow" },
    { name: "Maps To", latex: "\\mapsto" },
    { name: "Long Maps To", latex: "\\longmapsto" },
    { name: "Near Arrow", latex: "\\nearrow" },
    { name: "Hook Left Arrow", latex: "\\hookleftarrow" },
    { name: "Hook Right Arrow", latex: "\\hookrightarrow" },
    { name: "Search Arrow", latex: "\\searrow" },
    { name: "Left Harpoon Up", latex: "\\leftharpoonup" },
    { name: "Right Harpoon Up", latex: "\\rightharpoonup" },
    { name: "Southwest Arrow", latex: "\\swarrow" },
    { name: "Left Harpoon Down", latex: "\\leftharpoondown" },
    { name: "Right Harpoon Down", latex: "\\rightharpoondown" },
    { name: "Northwest Arrow", latex: "\\nwarrow" },
];

export const latinSymbols: SymbolItem[] = [
    { name: "ö", latex: "\\ddot{o}" },
    { name: "ò", latex: "\\grave{o}" },
    { name: "ó", latex: "\\acute{o}" },
    { name: "ô", latex: "\\hat{o}" },
    { name: "õ", latex: "\\tilde{o}" },
    { name: "ō", latex: "\\bar{o}" },
    { name: "ȯ", latex: "\\dot{o}" },
    { name: "ŏ", latex: "\\breve{o}" },
    { name: "ǒ", latex: "\\check{o}" },
    { name: "ő", latex: "\\H{o}" },
    { name: "o̧", latex: "\\text{o̧}" },
    { name: "ọ", latex: "\\text{ọ}" },
    { name: "o̲", latex: "\\underline{o}" },
    { name: "oo", latex: "o\\!\\!-\\!\\!o" },
    { name: "œ", latex: "\\text{œ}" },
    { name: "Œ", latex: "\\text{Œ}" },
    { name: "æ", latex: "\\text{æ}" },
    { name: "Æ", latex: "\\text{Æ}" },
    { name: "å", latex: "\\text{å}" },
    { name: "Å", latex: "\\text{Å}" },
    { name: "ø", latex: "\\text{ø}" },
    { name: "Ø", latex: "\\text{Ø}" },
    { name: "ł", latex: "\\text{ł}" },
    { name: "Ł", latex: "\\text{Ł}" },
    { name: "ı", latex: "\\imath" },
    { name: "ȷ", latex: "\\jmath" },
    { name: "¿", latex: "\\text{¿}" },
    { name: "¡", latex: "\\text{¡}" },
];

// Set Theory Symbols
export const setTheorySymbols: SymbolItem[] = [
    { name: "Empty Set", latex: "\\emptyset" },
    { name: "Empty Set (Variant)", latex: "\\varnothing" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Contains", latex: "\\ni" },
    { name: "Subset", latex: "\\subset" },
    { name: "Subset or Equal", latex: "\\subseteq" },
    { name: "Not Subset", latex: "\\not\\subset" },
    { name: "Proper Subset", latex: "\\subsetneq" },
    { name: "Superset", latex: "\\supset" },
    { name: "Superset or Equal", latex: "\\supseteq" },
    { name: "Union", latex: "\\cup" },
    { name: "Intersection", latex: "\\cap" },
    { name: "Big Union", latex: "\\bigcup" },
    { name: "Big Intersection", latex: "\\bigcap" },
    { name: "Set Difference", latex: "\\setminus" },
    { name: "Complement", latex: "\\complement" },
    { name: "Natural Numbers", latex: "\\mathbb{N}" },
    { name: "Integers", latex: "\\mathbb{Z}" },
    { name: "Rational Numbers", latex: "\\mathbb{Q}" },
    { name: "Real Numbers", latex: "\\mathbb{R}" },
    { name: "Complex Numbers", latex: "\\mathbb{C}" },
    { name: "Power Set", latex: "\\mathcal{P}" },
    { name: "Cardinality", latex: "|A|" },
    { name: "Aleph", latex: "\\aleph" },
];

// Logic & Proof Symbols
export const logicSymbols: SymbolItem[] = [
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Not Exists", latex: "\\nexists" },
    { name: "Negation", latex: "\\neg" },
    { name: "Logical And", latex: "\\land" },
    { name: "Logical Or", latex: "\\lor" },
    { name: "Implies", latex: "\\Rightarrow" },
    { name: "Implied By", latex: "\\Leftarrow" },
    { name: "If and Only If", latex: "\\Leftrightarrow" },
    { name: "Long Implies", latex: "\\implies" },
    { name: "Long Iff", latex: "\\iff" },
    { name: "Proves", latex: "\\vdash" },
    { name: "Models", latex: "\\models" },
    { name: "Therefore", latex: "\\therefore" },
    { name: "Because", latex: "\\because" },
    { name: "Contradiction", latex: "\\bot" },
    { name: "Tautology", latex: "\\top" },
    { name: "QED", latex: "\\square" },
    { name: "Equivalent", latex: "\\equiv" },
    { name: "Not Equivalent", latex: "\\not\\equiv" },
];

// Linear Algebra Symbols
export const linearAlgebraSymbols: SymbolItem[] = [
    { name: "Vector", latex: "\\vec{x}" },
    { name: "Bold Vector", latex: "\\mathbf{x}" },
    { name: "Hat Vector", latex: "\\hat{x}" },
    { name: "Transpose", latex: "A^{\\top}" },
    { name: "Transpose (T)", latex: "A^T" },
    { name: "Inverse", latex: "A^{-1}" },
    { name: "Determinant", latex: "\\det(A)" },
    { name: "Determinant Bars", latex: "|A|" },
    { name: "Trace", latex: "\\text{tr}(A)" },
    { name: "Rank", latex: "\\text{rank}(A)" },
    { name: "Norm", latex: "\\lVert x \\rVert" },
    { name: "Norm (Double)", latex: "\\| x \\|" },
    { name: "Inner Product", latex: "\\langle x, y \\rangle" },
    { name: "Tensor Product", latex: "\\otimes" },
    { name: "Direct Sum", latex: "\\oplus" },
    { name: "Dot Product", latex: "\\cdot" },
    { name: "Cross Product", latex: "\\times" },
    { name: "Kronecker Delta", latex: "\\delta_{ij}" },
    { name: "Identity Matrix", latex: "I_n" },
    { name: "Zero Matrix", latex: "\\mathbf{0}" },
    { name: "Eigenvalue", latex: "\\lambda" },
    { name: "Matrix", latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}" },
    { name: "Column Vector", latex: "\\begin{pmatrix} x \\\\ y \\end{pmatrix}" },
];

// Calculus & Analysis Symbols
export const calculusSymbols: SymbolItem[] = [
    { name: "Partial Derivative", latex: "\\partial" },
    { name: "Nabla/Gradient", latex: "\\nabla" },
    { name: "Integral", latex: "\\int" },
    { name: "Definite Integral", latex: "\\int_{a}^{b}" },
    { name: "Double Integral", latex: "\\iint" },
    { name: "Triple Integral", latex: "\\iiint" },
    { name: "Contour Integral", latex: "\\oint" },
    { name: "Derivative", latex: "\\frac{d}{dx}" },
    { name: "Partial Derivative Frac", latex: "\\frac{\\partial}{\\partial x}" },
    { name: "Limit", latex: "\\lim_{x \\to a}" },
    { name: "Limit to Infinity", latex: "\\lim_{x \\to \\infty}" },
    { name: "Infinity", latex: "\\infty" },
    { name: "Summation", latex: "\\sum_{n=1}^{\\infty}" },
    { name: "Product", latex: "\\prod_{n=1}^{\\infty}" },
    { name: "Differential", latex: "dx" },
    { name: "Prime Derivative", latex: "f'(x)" },
    { name: "Double Prime", latex: "f''(x)" },
    { name: "Dot Derivative", latex: "\\dot{x}" },
    { name: "Double Dot", latex: "\\ddot{x}" },
    { name: "Approaches", latex: "\\to" },
    { name: "Evaluated At", latex: "\\Big|_{a}^{b}" },
];

// Probability & Statistics Symbols
export const probabilitySymbols: SymbolItem[] = [
    { name: "Probability", latex: "\\mathbb{P}" },
    { name: "Probability of A", latex: "P(A)" },
    { name: "Expectation", latex: "\\mathbb{E}[X]" },
    { name: "Expectation (E)", latex: "E[X]" },
    { name: "Variance", latex: "\\text{Var}(X)" },
    { name: "Covariance", latex: "\\text{Cov}(X,Y)" },
    { name: "Standard Deviation", latex: "\\sigma" },
    { name: "Mean", latex: "\\mu" },
    { name: "Sample Mean", latex: "\\bar{x}" },
    { name: "Distributed As", latex: "\\sim" },
    { name: "Normal Distribution", latex: "\\mathcal{N}(\\mu, \\sigma^2)" },
    { name: "Independent", latex: "\\perp" },
    { name: "Independent (Double)", latex: "\\perp\\!\\!\\!\\perp" },
    { name: "Conditional", latex: "\\mid" },
    { name: "Given", latex: "P(A \\mid B)" },
    { name: "Correlation", latex: "\\rho" },
    { name: "Chi-Squared", latex: "\\chi^2" },
    { name: "Binomial Coefficient", latex: "\\binom{n}{k}" },
    { name: "Factorial", latex: "n!" },
    { name: "Proportional To", latex: "\\propto" },
];

// Computer Science / Algorithms Symbols
export const csSymbols: SymbolItem[] = [
    { name: "Big O", latex: "O(n)" },
    { name: "Big Omega", latex: "\\Omega(n)" },
    { name: "Big Theta", latex: "\\Theta(n)" },
    { name: "Little o", latex: "o(n)" },
    { name: "Little omega", latex: "\\omega(n)" },
    { name: "Maps To", latex: "\\mapsto" },
    { name: "Assignment", latex: ":=" },
    { name: "Definition", latex: "\\triangleq" },
    { name: "Equivalent", latex: "\\equiv" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "XOR", latex: "\\oplus" },
    { name: "Logical And", latex: "\\land" },
    { name: "Logical Or", latex: "\\lor" },
    { name: "Negation", latex: "\\neg" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Modulo", latex: "\\bmod" },
    { name: "Divides", latex: "\\mid" },
    { name: "Does Not Divide", latex: "\\nmid" },
    { name: "Asterisk", latex: "\\ast" },
    { name: "Star", latex: "\\star" },
    { name: "Logarithm", latex: "\\log" },
    { name: "Natural Log", latex: "\\ln" },
];

// Number Theory Symbols
export const numberTheorySymbols: SymbolItem[] = [
    { name: "Divides", latex: "\\mid" },
    { name: "Does Not Divide", latex: "\\nmid" },
    { name: "GCD", latex: "\\gcd(a, b)" },
    { name: "LCM", latex: "\\text{lcm}(a, b)" },
    { name: "Congruent", latex: "\\equiv" },
    { name: "Modulo", latex: "\\pmod{n}" },
    { name: "Euler Phi", latex: "\\varphi(n)" },
    { name: "Phi Function", latex: "\\phi(n)" },
    { name: "Prime", latex: "p" },
    { name: "Prime Notation", latex: "p_n" },
    { name: "Coprime", latex: "\\perp" },
    { name: "Legendre Symbol", latex: "\\left(\\frac{a}{p}\\right)" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Integer Part", latex: "[x]" },
    { name: "Fractional Part", latex: "\\{x\\}" },
    { name: "Sum of Divisors", latex: "\\sigma(n)" },
    { name: "Mobius Function", latex: "\\mu(n)" },
    { name: "Number of Divisors", latex: "d(n)" },
];

// Physics Symbols
export const physicsSymbols: SymbolItem[] = [
    { name: "Planck Constant", latex: "\\hbar" },
    { name: "Bra", latex: "\\langle \\psi |" },
    { name: "Ket", latex: "| \\psi \\rangle" },
    { name: "Braket", latex: "\\langle \\phi | \\psi \\rangle" },
    { name: "Delta", latex: "\\Delta" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Laplacian", latex: "\\nabla^2" },
    { name: "D'Alembertian", latex: "\\Box" },
    { name: "Lagrangian", latex: "\\mathcal{L}" },
    { name: "Hamiltonian", latex: "\\mathcal{H}" },
    { name: "Wave Function", latex: "\\Psi" },
    { name: "Angular Frequency", latex: "\\omega" },
    { name: "Wavelength", latex: "\\lambda" },
    { name: "Tensor", latex: "T^{\\mu\\nu}" },
    { name: "Christoffel Symbol", latex: "\\Gamma^{\\lambda}_{\\mu\\nu}" },
    { name: "Partial Time", latex: "\\frac{\\partial}{\\partial t}" },
    { name: "Vector Field", latex: "\\vec{E}" },
    { name: "Cross Product", latex: "\\times" },
    { name: "Divergence", latex: "\\nabla \\cdot" },
    { name: "Curl", latex: "\\nabla \\times" },
];

// Chemistry Symbols
export const chemistrySymbols: SymbolItem[] = [
    { name: "Equilibrium Arrow", latex: "\\rightleftharpoons" },
    { name: "Reversible Reaction", latex: "\\leftrightarrows" },
    { name: "Right Arrow", latex: "\\rightarrow" },
    { name: "Yields", latex: "\\longrightarrow" },
    { name: "Up Arrow (Gas)", latex: "\\uparrow" },
    { name: "Down Arrow (Precipitate)", latex: "\\downarrow" },
    { name: "Isotope", latex: "{}^{14}_{6}\\text{C}" },
    { name: "Superscript Charge", latex: "\\text{Na}^{+}" },
    { name: "Subscript Count", latex: "\\text{H}_2\\text{O}" },
    { name: "Delta (Heat)", latex: "\\Delta" },
    { name: "Degree", latex: "^{\\circ}" },
    { name: "Celsius", latex: "^{\\circ}\\text{C}" },
    { name: "Bond", latex: "\\text{C}-\\text{C}" },
    { name: "Double Bond", latex: "\\text{C}=\\text{C}" },
    { name: "Triple Bond", latex: "\\text{C}\\equiv\\text{C}" },
    { name: "Partial Charge", latex: "\\delta^{+}" },
    { name: "Electron", latex: "e^{-}" },
    { name: "Aqueous", latex: "\\text{(aq)}" },
    { name: "Solid", latex: "\\text{(s)}" },
    { name: "Liquid", latex: "\\text{(l)}" },
    { name: "Gas", latex: "\\text{(g)}" },
];

// Brackets & Delimiters
export const bracketSymbols: SymbolItem[] = [
    { name: "Angle Bracket Left", latex: "\\langle" },
    { name: "Angle Bracket Right", latex: "\\rangle" },
    { name: "Angle Brackets", latex: "\\langle x \\rangle" },
    { name: "Ceiling Left", latex: "\\lceil" },
    { name: "Ceiling Right", latex: "\\rceil" },
    { name: "Ceiling", latex: "\\lceil x \\rceil" },
    { name: "Floor Left", latex: "\\lfloor" },
    { name: "Floor Right", latex: "\\rfloor" },
    { name: "Floor", latex: "\\lfloor x \\rfloor" },
    { name: "Double Vertical Bar", latex: "\\|" },
    { name: "Norm", latex: "\\| x \\|" },
    { name: "Double Bracket Left", latex: "\\llbracket" },
    { name: "Double Bracket Right", latex: "\\rrbracket" },
    { name: "Double Brackets", latex: "\\llbracket x \\rrbracket" },
    { name: "Parentheses", latex: "\\left( x \\right)" },
    { name: "Square Brackets", latex: "\\left[ x \\right]" },
    { name: "Curly Braces", latex: "\\left\\{ x \\right\\}" },
    { name: "Vertical Bar", latex: "\\left| x \\right|" },
    { name: "Big Parentheses", latex: "\\Big( x \\Big)" },
    { name: "Bigg Parentheses", latex: "\\Bigg( x \\Bigg)" },
    { name: "Left Only", latex: "\\left( x \\right." },
    { name: "Right Only", latex: "\\left. x \\right)" },
    { name: "Mixed Brackets", latex: "\\left[ x \\right)" },
];

// Accents & Modifiers
export const accentSymbols: SymbolItem[] = [
    { name: "Hat", latex: "\\hat{x}" },
    { name: "Wide Hat", latex: "\\widehat{xyz}" },
    { name: "Tilde", latex: "\\tilde{x}" },
    { name: "Wide Tilde", latex: "\\widetilde{xyz}" },
    { name: "Dot", latex: "\\dot{x}" },
    { name: "Double Dot", latex: "\\ddot{x}" },
    { name: "Triple Dot", latex: "\\dddot{x}" },
    { name: "Bar", latex: "\\bar{x}" },
    { name: "Overline", latex: "\\overline{xyz}" },
    { name: "Underline", latex: "\\underline{xyz}" },
    { name: "Vector Arrow", latex: "\\vec{x}" },
    { name: "Wide Vector", latex: "\\overrightarrow{AB}" },
    { name: "Left Vector", latex: "\\overleftarrow{AB}" },
    { name: "Double Arrow", latex: "\\overleftrightarrow{AB}" },
    { name: "Acute", latex: "\\acute{x}" },
    { name: "Grave", latex: "\\grave{x}" },
    { name: "Breve", latex: "\\breve{x}" },
    { name: "Check", latex: "\\check{x}" },
    { name: "Ring", latex: "\\mathring{x}" },
    { name: "Overbrace", latex: "\\overbrace{x+y}^{\\text{sum}}" },
    { name: "Underbrace", latex: "\\underbrace{x+y}_{\\text{sum}}" },
    { name: "Cancel", latex: "\\cancel{x}" },
    { name: "Box", latex: "\\boxed{x}" },
];

// Currency & Finance Symbols
export const financeSymbols: SymbolItem[] = [
    { name: "Dollar", latex: "\\$" },
    { name: "Euro", latex: "\\text{€}" },
    { name: "Pound", latex: "\\text{£}" },
    { name: "Yen", latex: "\\text{¥}" },
    { name: "Rupee", latex: "\\text{₹}" },
    { name: "Bitcoin", latex: "\\text{₿}" },
    { name: "Percent", latex: "\\%" },
    { name: "Per Mille", latex: "\\text{‰}" },
    { name: "Basis Point", latex: "\\text{bp}" },
    { name: "NPV", latex: "\\text{NPV}" },
    { name: "IRR", latex: "\\text{IRR}" },
    { name: "ROI", latex: "\\text{ROI}" },
    { name: "Summation", latex: "\\sum_{t=1}^{n}" },
    { name: "Present Value", latex: "\\frac{C}{(1+r)^t}" },
    { name: "Compound Interest", latex: "A = P(1 + r/n)^{nt}" },
    { name: "Continuous Compounding", latex: "A = Pe^{rt}" },
    { name: "Greater Than", latex: ">" },
    { name: "Less Than", latex: "<" },
    { name: "Approximately", latex: "\\approx" },
    { name: "Plus Minus", latex: "\\pm" },
];

// Geometry Symbols
export const geometrySymbols: SymbolItem[] = [
    { name: "Angle", latex: "\\angle" },
    { name: "Measured Angle", latex: "\\measuredangle" },
    { name: "Spherical Angle", latex: "\\sphericalangle" },
    { name: "Triangle", latex: "\\triangle" },
    { name: "Square", latex: "\\square" },
    { name: "Circle", latex: "\\circ" },
    { name: "Perpendicular", latex: "\\perp" },
    { name: "Parallel", latex: "\\parallel" },
    { name: "Not Parallel", latex: "\\nparallel" },
    { name: "Congruent", latex: "\\cong" },
    { name: "Not Congruent", latex: "\\ncong" },
    { name: "Similar", latex: "\\sim" },
    { name: "Similar or Equal", latex: "\\simeq" },
    { name: "Arc", latex: "\\frown" },
    { name: "Degree", latex: "^{\\circ}" },
    { name: "Prime (feet/minutes)", latex: "'" },
    { name: "Double Prime (inches/seconds)", latex: "''" },
    { name: "Right Angle", latex: "\\perp" },
    { name: "Line Segment", latex: "\\overline{AB}" },
    { name: "Ray", latex: "\\overrightarrow{AB}" },
    { name: "Line", latex: "\\overleftrightarrow{AB}" },
    { name: "Pi (circle constant)", latex: "\\pi" },
    { name: "Diameter", latex: "\\varnothing" },
];

// Topology & Abstract Math Symbols
export const topologySymbols: SymbolItem[] = [
    { name: "Boundary", latex: "\\partial" },
    { name: "Aleph", latex: "\\aleph" },
    { name: "Aleph Null", latex: "\\aleph_0" },
    { name: "Aleph One", latex: "\\aleph_1" },
    { name: "Beth", latex: "\\beth" },
    { name: "Weierstrass P", latex: "\\wp" },
    { name: "Real Part", latex: "\\Re" },
    { name: "Imaginary Part", latex: "\\Im" },
    { name: "Homotopy", latex: "\\simeq" },
    { name: "Homeomorphic", latex: "\\cong" },
    { name: "Open Set", latex: "\\mathcal{O}" },
    { name: "Closure", latex: "\\overline{A}" },
    { name: "Interior", latex: "A^{\\circ}" },
    { name: "Exterior", latex: "\\text{ext}(A)" },
    { name: "Boundary Operator", latex: "\\partial A" },
    { name: "Direct Limit", latex: "\\varinjlim" },
    { name: "Inverse Limit", latex: "\\varprojlim" },
    { name: "Tensor Product", latex: "\\otimes" },
    { name: "Wedge Product", latex: "\\wedge" },
    { name: "Star Operator", latex: "\\star" },
    { name: "Quotient", latex: "A / B" },
    { name: "Fundamental Group", latex: "\\pi_1" },
    { name: "Homology", latex: "H_n" },
    { name: "Cohomology", latex: "H^n" },
    { name: "Category", latex: "\\mathcal{C}" },
    { name: "Functor", latex: "\\mathcal{F}" },
];

// Information Theory & Machine Learning Symbols
export const mlSymbols: SymbolItem[] = [
    { name: "Loss Function", latex: "\\mathcal{L}" },
    { name: "Expectation", latex: "\\mathbb{E}" },
    { name: "Expectation of X", latex: "\\mathbb{E}[X]" },
    { name: "KL Divergence", latex: "D_{\\text{KL}}(P \\| Q)" },
    { name: "KL Divergence Alt", latex: "\\text{KL}(P \\| Q)" },
    { name: "Argmax", latex: "\\arg\\max" },
    { name: "Argmin", latex: "\\arg\\min" },
    { name: "Argmax Subscript", latex: "\\arg\\max_{\\theta}" },
    { name: "Argmin Subscript", latex: "\\arg\\min_{\\theta}" },
    { name: "Tensor Product", latex: "\\otimes" },
    { name: "Hadamard Product", latex: "\\odot" },
    { name: "Softmax", latex: "\\text{softmax}" },
    { name: "Sigmoid", latex: "\\sigma" },
    { name: "ReLU", latex: "\\text{ReLU}" },
    { name: "Gradient", latex: "\\nabla" },
    { name: "Gradient of L", latex: "\\nabla_{\\theta} \\mathcal{L}" },
    { name: "Partial Derivative", latex: "\\frac{\\partial \\mathcal{L}}{\\partial \\theta}" },
    { name: "Learning Rate", latex: "\\eta" },
    { name: "Theta (parameters)", latex: "\\theta" },
    { name: "Theta Star", latex: "\\theta^*" },
    { name: "Weight Matrix", latex: "\\mathbf{W}" },
    { name: "Bias Vector", latex: "\\mathbf{b}" },
    { name: "Cross Entropy", latex: "H(p, q)" },
    { name: "Entropy", latex: "H(X)" },
    { name: "Mutual Information", latex: "I(X; Y)" },
    { name: "Log Likelihood", latex: "\\log p(x | \\theta)" },
    { name: "Probability Distribution", latex: "p(x)" },
    { name: "Conditional Probability", latex: "p(y | x)" },
    { name: "Sum Over Classes", latex: "\\sum_{c=1}^{C}" },
    { name: "Product Over Samples", latex: "\\prod_{i=1}^{N}" },
    { name: "L1 Norm", latex: "\\| \\theta \\|_1" },
    { name: "L2 Norm", latex: "\\| \\theta \\|_2" },
    { name: "Frobenius Norm", latex: "\\| \\mathbf{W} \\|_F" },
];

// Relations & Comparisons
export const relationSymbols: SymbolItem[] = [
    { name: "Less Than", latex: "<" },
    { name: "Greater Than", latex: ">" },
    { name: "Less Than or Equal", latex: "\\leq" },
    { name: "Greater Than or Equal", latex: "\\geq" },
    { name: "Not Equal", latex: "\\neq" },
    { name: "Approximately Equal", latex: "\\approx" },
    { name: "Equivalent", latex: "\\equiv" },
    { name: "Proportional To", latex: "\\propto" },
    { name: "Similar To", latex: "\\sim" },
    { name: "Congruent", latex: "\\cong" },
    { name: "Subset", latex: "\\subset" },
    { name: "Subset or Equal", latex: "\\subseteq" },
    { name: "Proper Subset", latex: "\\subsetneq" },
    { name: "Superset", latex: "\\supset" },
    { name: "Superset or Equal", latex: "\\supseteq" },
    { name: "Perpendicular", latex: "\\perp" },
    { name: "Parallel", latex: "\\parallel" },
    { name: "Not Parallel", latex: "\\nparallel" },
    { name: "Much Less Than", latex: "\\ll" },
    { name: "Much Greater Than", latex: "\\gg" },
    { name: "Precedes", latex: "\\prec" },
    { name: "Succeeds", latex: "\\succ" },
    { name: "Precedes or Equal", latex: "\\preceq" },
    { name: "Succeeds or Equal", latex: "\\succeq" },
    { name: "Asymptotic", latex: "\\asymp" },
    { name: "Defined As", latex: ":=" },
    { name: "Triangle Equal", latex: "\\triangleq" },
];

// Operators (Advanced & Binary)
export const operatorSymbols: SymbolItem[] = [
    { name: "Direct Sum", latex: "\\oplus" },
    { name: "Tensor Product", latex: "\\otimes" },
    { name: "Circle Dot", latex: "\\odot" },
    { name: "Circle Minus", latex: "\\ominus" },
    { name: "Circle Slash", latex: "\\oslash" },
    { name: "Star", latex: "\\star" },
    { name: "Asterisk", latex: "\\ast" },
    { name: "Composition", latex: "\\circ" },
    { name: "Bullet", latex: "\\bullet" },
    { name: "Diamond", latex: "\\diamond" },
    { name: "Big Circle", latex: "\\bigcirc" },
    { name: "Triangle Up", latex: "\\triangle" },
    { name: "Triangle Down", latex: "\\triangledown" },
    { name: "Nabla", latex: "\\nabla" },
    { name: "Square", latex: "\\square" },
    { name: "Wedge", latex: "\\wedge" },
    { name: "Vee", latex: "\\vee" },
    { name: "Cup", latex: "\\cup" },
    { name: "Cap", latex: "\\cap" },
    { name: "Amalgamation", latex: "\\amalg" },
    { name: "Dagger", latex: "\\dagger" },
    { name: "Double Dagger", latex: "\\ddagger" },
    { name: "Wreath Product", latex: "\\wr" },
    { name: "Set Minus", latex: "\\setminus" },
];

// Summation & Product Notation
export const summationSymbols: SymbolItem[] = [
    { name: "Summation", latex: "\\sum" },
    { name: "Summation with Limits", latex: "\\sum_{i=1}^{n}" },
    { name: "Summation to Infinity", latex: "\\sum_{n=0}^{\\infty}" },
    { name: "Product", latex: "\\prod" },
    { name: "Product with Limits", latex: "\\prod_{i=1}^{n}" },
    { name: "Coproduct", latex: "\\coprod" },
    { name: "Big Union", latex: "\\bigcup" },
    { name: "Big Union with Index", latex: "\\bigcup_{i=1}^{n}" },
    { name: "Big Intersection", latex: "\\bigcap" },
    { name: "Big Intersection with Index", latex: "\\bigcap_{i=1}^{n}" },
    { name: "Big Wedge", latex: "\\bigwedge" },
    { name: "Big Vee", latex: "\\bigvee" },
    { name: "Big Direct Sum", latex: "\\bigoplus" },
    { name: "Big Tensor Product", latex: "\\bigotimes" },
    { name: "Big Circle Dot", latex: "\\bigodot" },
    { name: "Big Square Union", latex: "\\bigsqcup" },
    { name: "Double Sum", latex: "\\sum_{i=1}^{m} \\sum_{j=1}^{n}" },
    { name: "Indexed Sum", latex: "\\sum_{k \\in K}" },
];

// Functions & Mapping
export const functionSymbols: SymbolItem[] = [
    { name: "Function", latex: "f(x)" },
    { name: "Function Definition", latex: "f: A \\to B" },
    { name: "Maps To", latex: "\\mapsto" },
    { name: "Right Arrow", latex: "\\to" },
    { name: "Long Right Arrow", latex: "\\longrightarrow" },
    { name: "Composition", latex: "f \\circ g" },
    { name: "Inverse Function", latex: "f^{-1}" },
    { name: "Image", latex: "\\text{Im}(f)" },
    { name: "Kernel", latex: "\\ker(f)" },
    { name: "Domain", latex: "\\text{dom}(f)" },
    { name: "Codomain", latex: "\\text{cod}(f)" },
    { name: "Range", latex: "\\text{range}(f)" },
    { name: "Injective", latex: "\\hookrightarrow" },
    { name: "Surjective", latex: "\\twoheadrightarrow" },
    { name: "Bijective", latex: "\\leftrightarrow" },
    { name: "Restriction", latex: "f|_A" },
    { name: "Function Evaluation", latex: "f(x) = y" },
    { name: "Piecewise Function", latex: "f(x) = \\begin{cases} a & x > 0 \\\\ b & x \\leq 0 \\end{cases}" },
];

// Inequalities & Order Theory
export const orderSymbols: SymbolItem[] = [
    { name: "Less Than", latex: "<" },
    { name: "Greater Than", latex: ">" },
    { name: "Less Than or Equal", latex: "\\leq" },
    { name: "Greater Than or Equal", latex: "\\geq" },
    { name: "Much Less Than", latex: "\\ll" },
    { name: "Much Greater Than", latex: "\\gg" },
    { name: "Precedes", latex: "\\prec" },
    { name: "Succeeds", latex: "\\succ" },
    { name: "Precedes or Equal", latex: "\\preceq" },
    { name: "Succeeds or Equal", latex: "\\succeq" },
    { name: "Curly Precedes", latex: "\\preccurlyeq" },
    { name: "Curly Succeeds", latex: "\\succcurlyeq" },
    { name: "Not Less Than", latex: "\\nless" },
    { name: "Not Greater Than", latex: "\\ngtr" },
    { name: "Not Less or Equal", latex: "\\nleq" },
    { name: "Not Greater or Equal", latex: "\\ngeq" },
    { name: "Minimum", latex: "\\min" },
    { name: "Maximum", latex: "\\max" },
    { name: "Infimum", latex: "\\inf" },
    { name: "Supremum", latex: "\\sup" },
    { name: "Least Upper Bound", latex: "\\text{lub}" },
    { name: "Greatest Lower Bound", latex: "\\text{glb}" },
];

// Logic Gates & Boolean Algebra
export const booleanSymbols: SymbolItem[] = [
    { name: "AND", latex: "\\land" },
    { name: "OR", latex: "\\lor" },
    { name: "NOT", latex: "\\neg" },
    { name: "XOR", latex: "\\oplus" },
    { name: "NAND", latex: "\\barwedge" },
    { name: "NOR", latex: "\\bar{\\vee}" },
    { name: "XNOR", latex: "\\odot" },
    { name: "Implies", latex: "\\Rightarrow" },
    { name: "If and Only If", latex: "\\Leftrightarrow" },
    { name: "True", latex: "\\top" },
    { name: "False", latex: "\\bot" },
    { name: "Boolean AND", latex: "A \\cdot B" },
    { name: "Boolean OR", latex: "A + B" },
    { name: "Boolean NOT", latex: "\\overline{A}" },
    { name: "Complement", latex: "A'" },
    { name: "De Morgan", latex: "\\overline{A \\cdot B} = \\overline{A} + \\overline{B}" },
];

// Optimization & Operations Research
export const optimizationSymbols: SymbolItem[] = [
    { name: "Argmax", latex: "\\arg\\max" },
    { name: "Argmin", latex: "\\arg\\min" },
    { name: "Argmax Subscript", latex: "\\arg\\max_{x}" },
    { name: "Argmin Subscript", latex: "\\arg\\min_{x}" },
    { name: "Minimize", latex: "\\min_{x}" },
    { name: "Maximize", latex: "\\max_{x}" },
    { name: "Subject To", latex: "\\text{s.t.}" },
    { name: "Constraint", latex: "g(x) \\leq 0" },
    { name: "Equality Constraint", latex: "h(x) = 0" },
    { name: "Lagrangian", latex: "\\mathcal{L}(x, \\lambda)" },
    { name: "Lambda (Multiplier)", latex: "\\lambda" },
    { name: "Gradient", latex: "\\nabla f(x)" },
    { name: "Hessian", latex: "\\nabla^2 f(x)" },
    { name: "Optimal Value", latex: "x^*" },
    { name: "Feasible Set", latex: "\\mathcal{X}" },
    { name: "Objective Function", latex: "f(x)" },
    { name: "Dual Variable", latex: "\\mu" },
    { name: "KKT Conditions", latex: "\\nabla f + \\lambda \\nabla g = 0" },
    { name: "Convex Set", latex: "\\mathcal{C}" },
    { name: "Positive Definite", latex: "\\succ 0" },
    { name: "Positive Semidefinite", latex: "\\succeq 0" },
];

// Units & Measurements
export const unitSymbols: SymbolItem[] = [
    { name: "Degree", latex: "^{\\circ}" },
    { name: "Prime (Minutes/Feet)", latex: "'" },
    { name: "Double Prime (Seconds/Inches)", latex: "''" },
    { name: "Angstrom", latex: "\\text{\\AA}" },
    { name: "Micro", latex: "\\mu" },
    { name: "Ohm", latex: "\\Omega" },
    { name: "H-bar (Planck)", latex: "\\hbar" },
    { name: "Celsius", latex: "^{\\circ}\\text{C}" },
    { name: "Fahrenheit", latex: "^{\\circ}\\text{F}" },
    { name: "Kelvin", latex: "\\text{K}" },
    { name: "Meter", latex: "\\text{m}" },
    { name: "Kilogram", latex: "\\text{kg}" },
    { name: "Second", latex: "\\text{s}" },
    { name: "Ampere", latex: "\\text{A}" },
    { name: "Volt", latex: "\\text{V}" },
    { name: "Watt", latex: "\\text{W}" },
    { name: "Joule", latex: "\\text{J}" },
    { name: "Newton", latex: "\\text{N}" },
    { name: "Pascal", latex: "\\text{Pa}" },
    { name: "Hertz", latex: "\\text{Hz}" },
    { name: "Per", latex: "/" },
    { name: "Squared", latex: "^2" },
    { name: "Cubed", latex: "^3" },
];

// Quantifiers
export const quantifierSymbols: SymbolItem[] = [
    { name: "For All", latex: "\\forall" },
    { name: "Exists", latex: "\\exists" },
    { name: "Not Exists", latex: "\\nexists" },
    { name: "Unique Exists", latex: "\\exists!" },
    { name: "Element Of", latex: "\\in" },
    { name: "Not Element Of", latex: "\\notin" },
    { name: "Contains", latex: "\\ni" },
    { name: "For All x", latex: "\\forall x" },
    { name: "Exists x", latex: "\\exists x" },
    { name: "For All in Set", latex: "\\forall x \\in A" },
    { name: "Exists in Set", latex: "\\exists x \\in A" },
    { name: "Such That", latex: "\\mid" },
    { name: "Such That (Colon)", latex: ":" },
    { name: "Set Builder", latex: "\\{ x \\mid P(x) \\}" },
    { name: "Quantified Statement", latex: "\\forall x \\exists y : P(x, y)" },
];

// Graph Theory
export const graphSymbols: SymbolItem[] = [
    { name: "Vertex", latex: "v" },
    { name: "Edge", latex: "e" },
    { name: "Graph", latex: "G = (V, E)" },
    { name: "Vertex Set", latex: "V(G)" },
    { name: "Edge Set", latex: "E(G)" },
    { name: "Adjacency", latex: "u \\sim v" },
    { name: "Degree", latex: "\\deg(v)" },
    { name: "In-Degree", latex: "\\deg^{-}(v)" },
    { name: "Out-Degree", latex: "\\deg^{+}(v)" },
    { name: "Path", latex: "P_n" },
    { name: "Cycle", latex: "C_n" },
    { name: "Complete Graph", latex: "K_n" },
    { name: "Bipartite", latex: "K_{m,n}" },
    { name: "Adjacency Matrix", latex: "A_{ij}" },
    { name: "Incidence Matrix", latex: "B" },
    { name: "Connected", latex: "u \\leftrightarrow v" },
    { name: "Tree", latex: "T" },
    { name: "Forest", latex: "F" },
    { name: "Chromatic Number", latex: "\\chi(G)" },
    { name: "Clique", latex: "\\omega(G)" },
    { name: "Independent Set", latex: "\\alpha(G)" },
    { name: "Matching", latex: "M" },
    { name: "Planar Graph", latex: "G \\hookrightarrow \\mathbb{R}^2" },
];

// Combinatorics
export const combinatoricsSymbols: SymbolItem[] = [
    { name: "Factorial", latex: "n!" },
    { name: "Binomial Coefficient", latex: "\\binom{n}{k}" },
    { name: "Combination (nCr)", latex: "C(n, k)" },
    { name: "Permutation (nPr)", latex: "P(n, k)" },
    { name: "Multinomial", latex: "\\binom{n}{k_1, k_2, \\ldots, k_m}" },
    { name: "Falling Factorial", latex: "(n)_k" },
    { name: "Rising Factorial", latex: "n^{(k)}" },
    { name: "Stirling First Kind", latex: "\\genfrac{[}{]}{0pt}{}{n}{k}" },
    { name: "Stirling Second Kind", latex: "\\genfrac{\\{}{\\}}{0pt}{}{n}{k}" },
    { name: "Bell Number", latex: "B_n" },
    { name: "Catalan Number", latex: "C_n" },
    { name: "Fibonacci", latex: "F_n" },
    { name: "Partition", latex: "p(n)" },
    { name: "Derangement", latex: "D_n" },
    { name: "Double Factorial", latex: "n!!" },
    { name: "Subfactorial", latex: "!n" },
    { name: "Pochhammer", latex: "(a)_n" },
    { name: "Counting Function", latex: "|A|" },
];

// Special Functions
export const specialFunctionSymbols: SymbolItem[] = [
    { name: "Gamma Function", latex: "\\Gamma(z)" },
    { name: "Beta Function", latex: "B(x, y)" },
    { name: "Riemann Zeta", latex: "\\zeta(s)" },
    { name: "Error Function", latex: "\\text{erf}(x)" },
    { name: "Complementary Error", latex: "\\text{erfc}(x)" },
    { name: "Bessel J", latex: "J_n(x)" },
    { name: "Bessel Y", latex: "Y_n(x)" },
    { name: "Modified Bessel I", latex: "I_n(x)" },
    { name: "Modified Bessel K", latex: "K_n(x)" },
    { name: "Legendre P", latex: "P_n(x)" },
    { name: "Legendre Q", latex: "Q_n(x)" },
    { name: "Hermite Polynomial", latex: "H_n(x)" },
    { name: "Laguerre Polynomial", latex: "L_n(x)" },
    { name: "Chebyshev T", latex: "T_n(x)" },
    { name: "Chebyshev U", latex: "U_n(x)" },
    { name: "Hypergeometric", latex: "{}_2F_1(a,b;c;z)" },
    { name: "Digamma", latex: "\\psi(x)" },
    { name: "Polygamma", latex: "\\psi^{(n)}(x)" },
    { name: "Elliptic Integral K", latex: "K(k)" },
    { name: "Elliptic Integral E", latex: "E(k)" },
    { name: "Dirac Delta", latex: "\\delta(x)" },
    { name: "Heaviside Step", latex: "H(x)" },
];

// Complex Numbers
export const complexSymbols: SymbolItem[] = [
    { name: "Complex Numbers", latex: "\\mathbb{C}" },
    { name: "Imaginary Unit", latex: "i" },
    { name: "Imaginary Unit (Engineering)", latex: "j" },
    { name: "Complex Number", latex: "z = a + bi" },
    { name: "Real Part", latex: "\\Re(z)" },
    { name: "Imaginary Part", latex: "\\Im(z)" },
    { name: "Complex Conjugate", latex: "\\bar{z}" },
    { name: "Complex Conjugate (Star)", latex: "z^*" },
    { name: "Modulus", latex: "|z|" },
    { name: "Argument", latex: "\\arg(z)" },
    { name: "Principal Argument", latex: "\\text{Arg}(z)" },
    { name: "Polar Form", latex: "r e^{i\\theta}" },
    { name: "Euler's Formula", latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta" },
    { name: "Complex Exponential", latex: "e^{z}" },
    { name: "Complex Logarithm", latex: "\\log z" },
    { name: "Complex Power", latex: "z^w" },
    { name: "Unit Circle", latex: "|z| = 1" },
    { name: "Upper Half Plane", latex: "\\mathbb{H}" },
    { name: "Complex Plane", latex: "\\mathbb{C}" },
];

// Trigonometry
export const trigSymbols: SymbolItem[] = [
    { name: "Sine", latex: "\\sin" },
    { name: "Cosine", latex: "\\cos" },
    { name: "Tangent", latex: "\\tan" },
    { name: "Cotangent", latex: "\\cot" },
    { name: "Secant", latex: "\\sec" },
    { name: "Cosecant", latex: "\\csc" },
    { name: "Arcsine", latex: "\\arcsin" },
    { name: "Arccosine", latex: "\\arccos" },
    { name: "Arctangent", latex: "\\arctan" },
    { name: "Arccotangent", latex: "\\text{arccot}" },
    { name: "Arcsecant", latex: "\\text{arcsec}" },
    { name: "Arccosecant", latex: "\\text{arccsc}" },
    { name: "Inverse Sine", latex: "\\sin^{-1}" },
    { name: "Inverse Cosine", latex: "\\cos^{-1}" },
    { name: "Inverse Tangent", latex: "\\tan^{-1}" },
    { name: "Hyperbolic Sine", latex: "\\sinh" },
    { name: "Hyperbolic Cosine", latex: "\\cosh" },
    { name: "Hyperbolic Tangent", latex: "\\tanh" },
    { name: "Inverse Hyperbolic Sine", latex: "\\text{arcsinh}" },
    { name: "Pi (Radians)", latex: "\\pi" },
    { name: "Degrees", latex: "^{\\circ}" },
    { name: "Radians", latex: "\\text{rad}" },
    { name: "Angle Theta", latex: "\\theta" },
    { name: "Angle Phi", latex: "\\phi" },
];

// Differential Geometry
export const diffGeoSymbols: SymbolItem[] = [
    { name: "Manifold", latex: "\\mathcal{M}" },
    { name: "Tangent Space", latex: "T_p M" },
    { name: "Cotangent Space", latex: "T^*_p M" },
    { name: "Tangent Bundle", latex: "TM" },
    { name: "Cotangent Bundle", latex: "T^*M" },
    { name: "Covariant Derivative", latex: "\\nabla_X Y" },
    { name: "Christoffel Symbol", latex: "\\Gamma^k_{ij}" },
    { name: "Riemann Curvature", latex: "R^l_{ijk}" },
    { name: "Ricci Tensor", latex: "R_{ij}" },
    { name: "Scalar Curvature", latex: "R" },
    { name: "Metric Tensor", latex: "g_{ij}" },
    { name: "Inverse Metric", latex: "g^{ij}" },
    { name: "Exterior Derivative", latex: "d\\omega" },
    { name: "Wedge Product", latex: "\\alpha \\wedge \\beta" },
    { name: "Lie Derivative", latex: "\\mathcal{L}_X" },
    { name: "Lie Bracket", latex: "[X, Y]" },
    { name: "Hodge Star", latex: "\\star" },
    { name: "Connection Form", latex: "\\omega^i_j" },
    { name: "Curvature Form", latex: "\\Omega^i_j" },
    { name: "Geodesic", latex: "\\gamma(t)" },
    { name: "Parallel Transport", latex: "P_{\\gamma}" },
];

// Tensor Notation
export const tensorSymbols: SymbolItem[] = [
    { name: "Tensor", latex: "T^{ij}_{kl}" },
    { name: "Covariant Index", latex: "T_{ij}" },
    { name: "Contravariant Index", latex: "T^{ij}" },
    { name: "Mixed Tensor", latex: "T^i_j" },
    { name: "Kronecker Delta", latex: "\\delta^i_j" },
    { name: "Levi-Civita", latex: "\\epsilon_{ijk}" },
    { name: "Einstein Summation", latex: "A^i B_i" },
    { name: "Tensor Product", latex: "A \\otimes B" },
    { name: "Contraction", latex: "T^i_i" },
    { name: "Metric Lowering", latex: "v_i = g_{ij} v^j" },
    { name: "Metric Raising", latex: "v^i = g^{ij} v_j" },
    { name: "Partial Derivative", latex: "\\partial_i" },
    { name: "Covariant Derivative", latex: "\\nabla_i" },
    { name: "Symmetrization", latex: "T_{(ij)}" },
    { name: "Antisymmetrization", latex: "T_{[ij]}" },
    { name: "Tensor Rank", latex: "(p, q)" },
    { name: "Basis Vector", latex: "e_i" },
    { name: "Dual Basis", latex: "e^i" },
    { name: "Component Transform", latex: "T'^{ij} = \\Lambda^i_k \\Lambda^j_l T^{kl}" },
];

// Modal Logic
export const modalSymbols: SymbolItem[] = [
    { name: "Necessarily", latex: "\\Box" },
    { name: "Possibly", latex: "\\Diamond" },
    { name: "Not Necessary", latex: "\\neg\\Box" },
    { name: "Not Possible", latex: "\\neg\\Diamond" },
    { name: "Necessary Implication", latex: "\\Box(p \\to q)" },
    { name: "Possible Conjunction", latex: "\\Diamond(p \\land q)" },
    { name: "Knows", latex: "K_a p" },
    { name: "Believes", latex: "B_a p" },
    { name: "Common Knowledge", latex: "C_G p" },
    { name: "Temporal Always", latex: "\\Box p" },
    { name: "Temporal Eventually", latex: "\\Diamond p" },
    { name: "Until", latex: "p \\mathcal{U} q" },
    { name: "Next", latex: "\\bigcirc p" },
    { name: "Accessibility", latex: "w R v" },
    { name: "Kripke Model", latex: "\\mathcal{M}, w \\models p" },
    { name: "Possible World", latex: "w" },
    { name: "Deontic Ought", latex: "O p" },
    { name: "Deontic Permitted", latex: "P p" },
];

// Game Theory
export const gameTheorySymbols: SymbolItem[] = [
    { name: "Player", latex: "i" },
    { name: "Strategy", latex: "s_i" },
    { name: "Strategy Set", latex: "S_i" },
    { name: "Strategy Profile", latex: "s = (s_1, \\ldots, s_n)" },
    { name: "Payoff Function", latex: "u_i(s)" },
    { name: "Expected Payoff", latex: "\\mathbb{E}[u_i]" },
    { name: "Best Response", latex: "BR_i(s_{-i})" },
    { name: "Nash Equilibrium", latex: "s^* = (s_1^*, \\ldots, s_n^*)" },
    { name: "Mixed Strategy", latex: "\\sigma_i" },
    { name: "Probability Simplex", latex: "\\Delta(S_i)" },
    { name: "Dominant Strategy", latex: "s_i^d" },
    { name: "Dominated Strategy", latex: "s_i \\prec s'_i" },
    { name: "Pareto Optimal", latex: "s^{PO}" },
    { name: "Minimax", latex: "\\min_j \\max_i" },
    { name: "Zero Sum", latex: "u_1 + u_2 = 0" },
    { name: "Cooperative Value", latex: "v(S)" },
    { name: "Shapley Value", latex: "\\phi_i(v)" },
    { name: "Subgame Perfect", latex: "SPE" },
    { name: "Information Set", latex: "h" },
    { name: "Action", latex: "a_i" },
];